spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl_auto: update
    show_sql: true